apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-graph-builder
  namespace: oasa-telemat
spec:
  schedule: "0 3 * * *"        # κάθε μέρα 03:00
  timeZone: "Europe/Athens"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: builder
              image: localhost:5000/trip-planner-job-02:0.0.1
              envFrom:
              - configMapRef:
                  name: trip-enviroment
              env:
                - name: TZ
                  value: "Europe/Athens"
                - name: OTP_JAVA_XMX
                  value: "8G"
                - name: OSM_URL
                  value: "https://download.geofabrik.de/europe/greece-latest.osm.pbf"
                - name: GTFS_FILE
                  value: "gtfs_feed.zip"
                - name: ROUTER_DIR
                  value: "/data/routers/default"
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: otp-shared-pvc