apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mysql-config
  namespace: oasa-telemat
configMapGenerator:
  - name: mysql-schema-config
    namespace: oasa-telemat
    files:
      - resources/oasa-telemat/schema_v2.sql
resources:
  - pvc.yaml
  - secret.yaml
  - config-mysql.yaml
  - deployment.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true # use a static name