apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: oasa-telemat
type: kubernetes.io/basic-auth
stringData:
  MYSQL_PASSWORD: user1Password
  MYSQL_USER: user1
  username: user1
  password: user1Password
  MYSQL_ROOT_PASSWORD: RootPassword
  MYSQL_DATABASE: oasa_telemat