apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: admin-panel
  namespace: oasa-telemat
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 5 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: admin-panel
        image: localhost:5000/oasa-portal:0.0.1 # Image that will be used to containers in the cluster
        ports:
        - containerPort: 80 # The port that the container is running on in the cluster
