kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: admin-service
  namespace: oasa-telemat
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 80   # The port that the service is running on in the cluster
    targetPort: 80   # The port exposed by the service
    nodePort: 31000
  type: NodePort     # type of the service.
