apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql-depl
  name: mysql-depl
  namespace: oasa-telemat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-depl
  template:
    metadata:
      labels:
        app: mysql-depl
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
        image: mysql:8.4
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password
        ports:
          - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pvc-vol
        - nane: mysql-ext-pvc-vol
          mountPath: /var/lib/ext  
        - mountPath: /var/db/config/oasa-telemat
          name: mysql-schema-config-vol
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 2
      volumes:
      - name: mysql-pvc-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-schema-config-vol
        configMap:
          name: mysql-schema-config
          defaultMode: 420
          items:
          - key: schema_v2.sql
            path: mysql-schema-config.sql
      - name: mysql-ext-pvc-vol
        persistentVolumeClaim:
          claimName: mysql-ext-pvc
