apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oasa-server
  name: oasa-server
  namespace: oasa-telemat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oasa-server
  template:
    metadata:
      labels:
        app: oasa-server
    spec:
      initContainers:
        - name: wait-mysql
          image: mysql:8.4
          env:
            - name: MYSQL_HOST
              value: "mysql-svc"   # <-- your MySQL Service DNS
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          command: ["sh","-c"]
          args:
            - |
              set -e
              export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"
              until mysqladmin ping -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u root --silent; do
                echo "🟠 Waiting for MySQL at $MYSQL_HOST:$MYSQL_PORT ..."
                sleep 2
              done
              echo "🟢 MySQL is ready."

        - name: wait-keycloak-02
          image: busybox:1.36
          env:
            - name: KC_READY_URL
              value: "http://keycloak-svc:8081/auth/health/ready"
          command: ["sh","-c"]
          args:
            - |
              until wget -qO- $KC_READY_URL >/dev/null; do
                echo "🟠 Waiting for Keycloak..." 
                sleep 2
              done
              echo "🟢 Keycloak is ready."
      containers:
      - image: cs161079uniwa/oasa-server:0.0.3                                      
        name: oasa-server
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: server-enviroment

