apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-deployment
  namespace: oasa-telemat
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: otp-server
  template:
    metadata:
      labels:
        app: otp-server
    spec:
      containers:
      - name: otp-container
        image: localhost:5000/trip-planner-api:0.0.8
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: "Europe/Athens"
          - name: OTP_JAVA_XMX
            value: "8G"
          - name: ROUTER_DIR
            value: "/data/routers/default"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet: { path: /otp/actuators/health, port: http }
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /otp/actuators/health, port: http }
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
        volumeMounts:
        - name: data
          mountPath: /data  
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: otp-shared-pvc